#
# CSSE 132
# Rose-Hulman Institute of Technology
# Computer Science and Software Engineering
#
# Makefile - This is used to make the lab.  This is a file you need to hand in
#            after you modify it.  Don't forget to put your names on it!
#
# NAMES: Yuankai Wang, Evelyne Maquelin
#

part1: part1.c
	gcc -g -o part1 part1.c
part2: part2.c
	gcc -g -o part2 part2.c
